export const publicPages = {
  '/about': {
    title: 'About C360 Innovation Lab',
    eyebrow: 'Who We Are',
    description: 'C360 Innovation Lab helps young people turn curiosity into capability through clubs, mentorship, research, and enterprise development.',
    cta: ['Explore Programs', '/programs'],
    stats: [['2020', 'Founded'], ['500+', 'Youth Members'], ['40+', 'Active Clubs'], ['80+', 'Mentors'], ['12+', 'Partners']],
    sections: [
      ['Our Mission', 'Build a global ecosystem where young innovators can learn, experiment, collaborate, and launch ideas that improve their communities.', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80'],
      ['Our Approach', 'We combine practical learning, peer clubs, expert mentorship, and partner support so learners can move from idea to action.', 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80'],
      ['Our Community', 'Students, mentors, educators, founders, and partners work together across regions to support youth-led innovation.', 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80'],
      ['Research & Innovation', 'Support youth-led inquiry, experimentation, and practical research that informs better solutions and drives community impact.', 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80'],
      ['Financial Literacy', 'Practical money skills help learners manage resources, understand opportunity, and make stronger enterprise decisions.', 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?auto=format&fit=crop&w=800&q=80'],
      ['Competitions', 'Discover innovation challenges, pitch events, and project competitions for young builders to showcase their ideas.', 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Innovation Clubs', 'Hands-on project spaces.', '/clubs'],
      ['Mentor Network', 'Expert professional guidance.', '/mentorship'],
      ['Enterprise Pathways', 'From idea to venture.', '/incubation'],
      ['Research Lab', 'Evidence-driven prototyping.', '/research'],
      ['Financial Literacy', 'Budgeting and funding skills.', '/financial-literacy'],
      ['Partnerships', 'Collaborators and resources.', '/partnerships'],
      ['Competitions', 'Challenges and pitch events.', '/competitions'],
    ],
  },
  '/programs': {
    title: 'Programs',
    eyebrow: 'Learn By Building',
    description: 'Explore practical programs designed to help learners build skills, launch projects, and grow as innovators.',
    cta: ['Join a Program', '/register'],
    stats: [['6', 'Core Tracks'], ['80+', 'Mentors'], ['Global', 'Access'], ['40+', 'Active Clubs'], ['12+', 'Partners']],
    sections: [
      ['Innovation & Creativity', 'Use design thinking and rapid prototyping to solve real problems.', 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80'],
      ['Career Guidance', 'Build career clarity through mentorship, skill mapping, and portfolio development.', 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80'],
      ['Enterprise Development', 'Learn how to validate ideas, build business models, and pitch confidently.', 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80'],
      ['Research & Innovation', 'Conduct youth-led research, build prototypes, and test bold ideas through practical experimentation.', 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80'],
      ['Financial Literacy', 'Build personal finance, business finance, and funding readiness skills for life and enterprise.', 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?auto=format&fit=crop&w=800&q=80'],
      ['Incubation', 'Get structured support to refine, validate, prototype, and pitch your innovation or venture.', 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Digital Skills Bootcamp', 'Web and product skills.', '/learn'],
      ['Design Thinking Intensive', 'Research, frame, prototype.', '/learn'],
      ['Leadership Lab', 'Communication and teamwork.', '/clubs'],
      ['Research Canvas', 'Questions, methods, findings.', '/research'],
      ['Pitch Deck Template', 'Story, solution, market, ask.', '/resources'],
      ['Budget Builder', 'Income, costs, savings.', '/financial-literacy'],
      ['Innovation Challenges', 'Solve real-world problems.', '/competitions'],
      ['Mentorship Sessions', 'One-on-one expert guidance.', '/mentorship-sessions'],
    ],
  },
  '/clubs': {
    title: 'Innovation Clubs',
    eyebrow: 'Build With Peers',
    description: 'Join themed clubs where young innovators collaborate, create projects, and learn through practice.',
    cta: ['Create Account', '/register'],
    stats: [['40+', 'Active Clubs'], ['500+', 'Members'], ['12+', 'Partner Hubs'], ['80+', 'Mentors'], ['Global', 'Network']],
    sections: [
      ['Tech Innovators Club', 'Build software, hardware, and digital tools for real-world problems.', 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80'],
      ['Green Futures Club', 'Explore climate, sustainability, and circular economy projects.', 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80'],
      ['Young Entrepreneurs Club', 'Practice business design, pitching, and customer discovery.', 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80'],
      ['Science & Research Club', 'Conduct youth-led research projects and compete in national innovation challenges.', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80'],
      ['Creative Arts Club', 'Merge creativity with technology, design, media, and storytelling for social impact.', 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80'],
      ['Community Leaders Club', 'Develop leadership skills and drive community development projects worldwide.', 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Digital Skills Bootcamp', 'Web and product skills.', '/learn'],
      ['Design Thinking Intensive', 'Research, frame, prototype.', '/learn'],
      ['Pitch Deck Template', 'Story, solution, market, ask.', '/resources'],
      ['Project Canvas', 'Map problems, users, solutions.', '/resources'],
      ['Innovation Challenges', 'Hackathons and pitch events.', '/competitions'],
      ['Mentorship Sessions', 'Expert guidance for projects.', '/mentorship-sessions'],
    ],
  },
  '/resources': {
    title: 'Resources',
    eyebrow: 'Toolkits & Guides',
    description: 'Access guides, templates, and learning materials for clubs, projects, competitions, and entrepreneurship.',
    cta: ['Start Learning', '/learn'],
    stats: [['60+', 'Resources'], ['12', 'Toolkits'], ['24/7', 'Access'], ['6', 'Core Tracks'], ['500+', 'Youth Members']],
    sections: [
      ['Startup Toolkit', 'Templates for idea validation, customer discovery, and pitch preparation.', 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80'],
      ['Club Guides', 'Practical facilitation guides for meetings, challenges, and project sprints.', 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80'],
      ['Learning Library', 'Curated lessons for design thinking, financial literacy, research, and leadership.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80'],
      ['Mentorship Resources', 'Session prep guides, goal-setting templates, and portfolio review frameworks.', 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80'],
      ['Competition Toolkits', 'Hackathon briefs, pitch evaluation rubrics, and project submission guides.', 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80'],
      ['Financial Literacy Tools', 'Budget builders, pricing calculators, and funding readiness checklists.', 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Pitch Deck Template', 'Story, solution, market, ask.', '/programs'],
      ['Project Canvas', 'Map problems, users, solutions.', '/clubs'],
      ['Mentorship Prep Guide', 'Focused mentor sessions.', '/mentorship-sessions'],
      ['Budget Builder', 'Income, costs, savings.', '/financial-literacy'],
      ['Research Canvas', 'Questions, methods, findings.', '/research'],
      ['Digital Skills Bootcamp', 'Web and product skills.', '/learn'],
      ['Innovation Challenges', 'Guided briefs and submissions.', '/competitions'],
      ['Incubation Guide', 'Refine, validate, pitch.', '/incubation'],
    ],
  },
  '/contact': {
    title: 'Contact Us',
    eyebrow: 'Start A Conversation',
    description: 'Reach out to collaborate, join a program, support a club, or learn more about C360 Innovation Lab.',
    cta: ['Create Account', '/register'],
    stats: [['Global', 'Community'], ['48h', 'Typical Reply'], ['Open', 'Partnerships'], ['500+', 'Youth Members'], ['40+', 'Active Clubs']],
    sections: [
      ['General Inquiries', 'Ask about programs, clubs, resources, or learner access.', 'https://images.unsplash.com/photo-1423666639041-f56000c27a9a?auto=format&fit=crop&w=800&q=80'],
      ['Partnerships', 'Work with us to support youth innovation through mentorship, grants, or learning opportunities.', 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80'],
      ['Support', 'Get help with account access, applications, and dashboard features.', 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=800&q=80'],
      ['Media & Press', 'Share stories about youth innovation, club impact, and community development initiatives.', 'https://images.unsplash.com/photo-1504711434969-e33886168d9c?auto=format&fit=crop&w=800&q=80'],
      ['Volunteer & Mentor', 'Contribute your expertise as a mentor, workshop facilitator, or club advisor.', 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=800&q=80'],
      ['Collaborate', 'Partner on innovation challenges, research projects, or enterprise development programs.', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['General', 'hello@c360innovation.org'],
      ['Partnerships', 'partners@c360innovation.org'],
      ['Support', 'help@c360innovation.org'],
      ['Explore Programs', 'Browse tracks and bootcamps.', '/programs'],
      ['Join a Club', 'Connect with innovation peers.', '/clubs'],
      ['Visit Learn Workspace', 'AI study partner access.', '/learn'],
    ],
  },
  '/competitions': {
    title: 'Competitions',
    eyebrow: 'Challenge Yourself',
    description: 'Discover innovation challenges, pitch events, and project competitions for young builders.',
    cta: ['Prepare With Learn', '/learn'],
    stats: [['8+', 'Annual Challenges'], ['Global', 'Participation'], ['Mentor', 'Feedback'], ['500+', 'Youth Participants'], ['40+', 'Active Clubs']],
    sections: [
      ['Innovation Challenges', 'Solve real-world problems through guided briefs and team submissions.', 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80'],
      ['Pitch Events', 'Practice communicating your idea clearly to mentors, judges, and partners.', 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80'],
      ['Showcases', 'Share prototypes, research, and project outcomes with the wider community.', 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80'],
      ['Hackathons', 'Participate in focused build sprints to prototype practical digital tools and solutions.', 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80'],
      ['Sustainability Challenges', 'Create solutions for climate and circular economy problems facing local communities.', 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80'],
      ['Enterprise Pitches', 'Develop and present a venture concept with mentorship and partner feedback.', 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Digital Solutions Hackathon', 'Prototype a digital tool.', '/learn'],
      ['Sustainability Challenge', 'Climate and economy solutions.', '/clubs'],
      ['Youth Enterprise Pitch', 'Present your venture concept.', '/incubation'],
      ['Pitch Deck Template', 'Structure your story and ask.', '/resources'],
      ['Project Canvas', 'Map problems and solutions.', '/resources'],
      ['Mentorship Prep Guide', 'Prepare for feedback sessions.', '/resources'],
      ['Design Thinking Intensive', 'Strengthen your submission.', '/learn'],
      ['Innovation Clubs', 'Build your project with peers.', '/clubs'],
    ],
  },
  '/financial-literacy': {
    title: 'Financial Literacy',
    eyebrow: 'Money Skills',
    description: 'Learn budgeting, saving, pricing, funding, and financial decision-making for life and enterprise.',
    cta: ['Open Learning Workspace', '/learn'],
    stats: [['5', 'Modules'], ['Practical', 'Exercises'], ['Youth', 'Focused']],
    sections: [
      ['Personal Finance', 'Build habits for budgeting, saving, and managing money confidently.', 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80'],
      ['Business Finance', 'Understand pricing, costs, revenue, and cash flow.', 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?auto=format&fit=crop&w=800&q=80'],
      ['Funding Readiness', 'Prepare for grants, partnerships, and responsible investment conversations.', 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Budget Builder', 'Plan income and costs.'],
      ['Pricing Practice', 'Set sustainable prices.'],
      ['Funding Checklist', 'Prepare for support.'],
    ],
  },
  '/incubation': {
    title: 'Apply For Incubation',
    eyebrow: 'From Idea To Launch',
    description: 'Get structured support to refine, validate, prototype, and pitch your innovation or venture.',
    cta: ['Apply Now', '/register'],
    stats: [['12 weeks', 'Guided Support'], ['Mentors', 'Assigned'], ['Demo Day', 'Included']],
    sections: [
      ['Validate', 'Test your assumptions with users and evidence.', 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=800&q=80'],
      ['Prototype', 'Turn ideas into simple, testable solutions.', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80'],
      ['Pitch', 'Tell a clear story about the problem, solution, model, and impact.', 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Idea Review', 'Clarify problem and solution.'],
      ['Mentor Sessions', 'Expert guidance from experts.'],
      ['Demo Preparation', 'Present your progress.'],
    ],
  },
  '/mentorship': {
    title: 'Career Guidance & Mentorship',
    eyebrow: 'Guided Growth',
    description: 'Connect with mentors who help learners make better decisions, build skills, and move toward meaningful opportunities.',
    cta: ['Book A Session', '/mentorship-sessions'],
    stats: [['80+', 'Mentors'], ['1:1', 'Guidance'], ['Career', 'Support']],
    sections: [
      ['Career Clarity', 'Explore interests, strengths, pathways, and next steps.', 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80'],
      ['Skill Building', 'Get feedback on portfolios, projects, communication, and leadership.', 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80'],
      ['Opportunity Readiness', 'Prepare for internships, programs, competitions, and entrepreneurship.', 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Portfolio Review', 'Present projects better.'],
      ['Goal Setting', 'Create a growth plan.'],
      ['Mock Interviews', 'Practice your strengths.'],
    ],
  },
  '/mentorship-sessions': {
    title: 'Mentorship Sessions',
    eyebrow: 'Book & Prepare',
    description: 'Manage mentorship sessions and prepare focused questions so every conversation creates progress.',
    cta: ['Open Dashboard', '/dashboard'],
    stats: [['30 min', 'Typical Session'], ['Focused', 'Agenda'], ['Action', 'Plan']],
    sections: [
      ['Upcoming Sessions', 'Track your scheduled mentor conversations.', 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80'],
      ['Preparation', 'Write goals, questions, and context before the call.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80'],
      ['Follow Up', 'Turn advice into concrete actions and deadlines.', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Career Planning', 'Skills, roles, pathways.'],
      ['Project Feedback', 'Prototypes and pitches.'],
      ['Enterprise Guidance', 'Business model review.'],
    ],
  },
  '/research': {
    title: 'Research & Innovation',
    eyebrow: 'Evidence Into Action',
    description: 'Support youth-led inquiry, experimentation, and practical research that informs better solutions.',
    cta: ['Use Learn Workspace', '/learn'],
    stats: [['Inquiry', 'Led'], ['Prototype', 'Driven'], ['Impact', 'Focused']],
    sections: [
      ['Problem Research', 'Understand users, contexts, and root causes.', 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80'],
      ['Experimentation', 'Test ideas through small pilots and prototypes.', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80'],
      ['Knowledge Sharing', 'Document findings and share lessons with the community.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Research Canvas', 'Questions, methods, findings.'],
      ['Interview Guide', 'Better user conversations.'],
      ['Insight Report', 'Observations into decisions.'],
    ],
  },
  '/partnerships': {
    title: 'Grants & Partnerships',
    eyebrow: 'Grow Together',
    description: 'Partner with C360 to support youth innovation through mentorship, funding, programs, and learning resources.',
    cta: ['Contact Us', '/contact'],
    stats: [['12+', 'Partners'], ['Global', 'Network'], ['Youth', 'Impact']],
    sections: [
      ['Mentorship Partners', 'Contribute expertise and guidance to young innovators.', 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80'],
      ['Program Partners', 'Co-create learning opportunities, challenges, and incubation pathways.', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80'],
      ['Grant Partners', 'Support promising youth-led projects and community solutions.', 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Sponsor A Club', 'Support project-based learning.'],
      ['Host A Challenge', 'Youth teams solve problems.'],
      ['Fund A Project', 'Prototype to impact.'],
    ],
  },
  '/profile': {
    title: 'My Profile',
    eyebrow: 'Your Account',
    description: 'Manage your learning profile, interests, goals, and saved progress across C360.',
    cta: ['Go To Dashboard', '/dashboard'],
    stats: [['Personal', 'Profile'], ['Saved', 'Progress'], ['Learning', 'Goals']],
    sections: [
      ['Personal Details', 'Keep your name, contact, and profile information up to date.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80'],
      ['Learning Interests', 'Choose the topics and tracks that matter most to you.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80'],
      ['Progress', 'Review activity across programs, clubs, mentorship, and learning.', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Edit Profile', 'Update account details.'],
      ['Set Goals', 'Define what to build.'],
      ['View Activity', 'Saved resources and progress.'],
    ],
  },
  '/my-club': {
    title: 'My Club',
    eyebrow: 'Club Workspace',
    description: 'Track your club, activities, members, and project progress in one place.',
    cta: ['Explore Clubs', '/clubs'],
    stats: [['Active', 'Membership'], ['Projects', 'In Progress'], ['Peer', 'Learning']],
    sections: [
      ['Club Overview', 'See your club focus, meeting rhythm, and current priorities.', 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80'],
      ['Projects', 'Follow the ideas and prototypes your club is building.', 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80'],
      ['Members', 'Collaborate with peers and club leaders.', 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Meeting Notes', 'Capture decisions and steps.'],
      ['Project Board', 'Organize ideas and tasks.'],
      ['Club Resources', 'Session facilitation guides.'],
    ],
  },
  '/notifications': {
    title: 'Notifications',
    eyebrow: 'Updates',
    description: 'Review program reminders, mentorship updates, resource alerts, and club activity.',
    cta: ['Open Dashboard', '/dashboard'],
    stats: [['3', 'Unread'], ['Today', 'Latest'], ['Action', 'Ready']],
    sections: [
      ['Mentorship', 'Session confirmations, reminders, and follow-up notes.', 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=80'],
      ['Learning', 'New resources, program updates, and recommended next steps.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80'],
      ['Clubs', 'Meeting reminders, project updates, and announcements.', 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80'],
    ],
    cards: [
      ['Session Confirmed', 'Mentorship session confirmed.'],
      ['New Resource', 'Grant opportunity added.'],
      ['Club Update', 'New meeting agenda.'],
    ],
  },
  '/terms': {
    title: 'Terms of Use',
    eyebrow: 'Legal',
    description: 'Terms and conditions governing the use of C360 Innovation Lab platforms and services.',
    cta: ['Back to Home', '/'],
    stats: [['Last Updated', 'July 2026'], ['Effective', 'Immediately']],
    sections: [
      ['Acceptance', 'By using C360 Innovation Lab, you agree to these terms.'],
      ['User Accounts', 'You are responsible for maintaining the confidentiality of your account.'],
      ['Acceptable Use', 'Use the platform respectfully and lawfully.'],
      ['Intellectual Property', 'Content and materials remain the property of their respective owners.'],
      ['Termination', 'We reserve the right to suspend accounts that violate these terms.'],
      ['Limitation of Liability', 'C360 Innovation Lab is provided as-is without warranties.'],
    ],
    cards: [
      ['Account Responsibilities', 'Keep your credentials secure and report unauthorized access.'],
      ['Community Guidelines', 'Respect all users and maintain a safe learning environment.'],
      ['Contact', 'Questions about these terms? Reach out at help@c360innovation.org.'],
    ],
  },
  '/privacy': {
    title: 'Privacy Policy',
    eyebrow: 'Legal',
    description: 'How C360 Innovation Lab collects, uses, and protects your personal information.',
    cta: ['Back to Home', '/'],
    stats: [['Last Updated', 'July 2026'], ['Effective', 'Immediately']],
    sections: [
      ['Information We Collect', 'Account details, learning activity, and usage data to improve your experience.'],
      ['How We Use Data', 'To provide services, personalize learning, and communicate updates.'],
      ['Data Security', 'We use industry-standard measures to protect your information.'],
      ['Third Parties', 'We do not sell your personal data to third parties.'],
      ['Cookies', 'We use essential cookies for authentication and analytics.'],
      ['Your Rights', 'You can access, update, or delete your account data at any time.'],
    ],
    cards: [
      ['Data Access', 'Request a copy of the data we hold about you.'],
      ['Account Deletion', 'Delete your account and all associated data from settings.'],
      ['Contact', 'Privacy concerns? Reach out at help@c360innovation.org.'],
    ],
  },
};
