export const publicPages = {
  '/about': {
    title: 'About C360 Innovation Lab',
    eyebrow: 'Who We Are',
    description: 'C360 Innovation Lab helps young people turn curiosity into capability through clubs, mentorship, research, and enterprise development.',
    cta: ['Explore Programs', '/programs'],
    stats: [['2020', 'Founded'], ['500+', 'Youth Members'], ['40+', 'Active Clubs']],
    sections: [
      ['Our Mission', 'Build a global ecosystem where young innovators can learn, experiment, collaborate, and launch ideas that improve their communities.'],
      ['Our Approach', 'We combine practical learning, peer clubs, expert mentorship, and partner support so learners can move from idea to action.'],
      ['Our Community', 'Students, mentors, educators, founders, and partners work together across regions to support youth-led innovation.'],
    ],
    cards: [
      ['Innovation Clubs', 'Hands-on spaces for learners to build projects and practice leadership.'],
      ['Mentor Network', 'Guidance from experienced professionals and entrepreneurs.'],
      ['Enterprise Pathways', 'Support for ideas that can become ventures, programs, or community initiatives.'],
    ],
  },
  '/programs': {
    title: 'Programs',
    eyebrow: 'Learn By Building',
    description: 'Explore practical programs designed to help learners build skills, launch projects, and grow as innovators.',
    cta: ['Join a Program', '/register'],
    stats: [['6', 'Core Tracks'], ['80+', 'Mentors'], ['Global', 'Access']],
    sections: [
      ['Innovation & Creativity', 'Use design thinking and rapid prototyping to solve real problems.'],
      ['Career Guidance', 'Build career clarity through mentorship, skill mapping, and portfolio development.'],
      ['Enterprise Development', 'Learn how to validate ideas, build business models, and pitch confidently.'],
    ],
    cards: [
      ['Digital Skills Bootcamp', 'A practical track for web, product, and digital problem-solving skills.'],
      ['Design Thinking Intensive', 'A guided experience for researching users, framing problems, and prototyping ideas.'],
      ['Leadership Lab', 'A project-based track for communication, teamwork, and community leadership.'],
    ],
  },
  '/clubs': {
    title: 'Innovation Clubs',
    eyebrow: 'Build With Peers',
    description: 'Join themed clubs where young innovators collaborate, create projects, and learn through practice.',
    cta: ['Create Account', '/register'],
    stats: [['40+', 'Active Clubs'], ['500+', 'Members'], ['12+', 'Partner Hubs']],
    sections: [
      ['Tech Innovators Club', 'Build software, hardware, and digital tools for real-world problems.'],
      ['Green Futures Club', 'Explore climate, sustainability, and circular economy projects.'],
      ['Young Entrepreneurs Club', 'Practice business design, pitching, and customer discovery.'],
    ],
    cards: [
      ['Creative Arts Club', 'Use design, media, and storytelling to create social impact.'],
      ['Research Club', 'Turn questions into projects through evidence, experiments, and reports.'],
      ['Community Leaders Club', 'Lead initiatives that solve local and global community challenges.'],
    ],
  },
  '/resources': {
    title: 'Resources',
    eyebrow: 'Toolkits & Guides',
    description: 'Access guides, templates, and learning materials for clubs, projects, competitions, and entrepreneurship.',
    cta: ['Start Learning', '/learn'],
    stats: [['60+', 'Resources'], ['12', 'Toolkits'], ['24/7', 'Access']],
    sections: [
      ['Startup Toolkit', 'Templates for idea validation, customer discovery, and pitch preparation.'],
      ['Club Guides', 'Practical facilitation guides for meetings, challenges, and project sprints.'],
      ['Learning Library', 'Curated lessons for design thinking, financial literacy, research, and leadership.'],
    ],
    cards: [
      ['Pitch Deck Template', 'Structure your story, solution, market, model, and ask.'],
      ['Project Canvas', 'Map problems, users, solutions, risks, and next steps.'],
      ['Mentorship Prep Guide', 'Make every mentor session focused and useful.'],
    ],
  },
  '/contact': {
    title: 'Contact Us',
    eyebrow: 'Start A Conversation',
    description: 'Reach out to collaborate, join a program, support a club, or learn more about C360 Innovation Lab.',
    cta: ['Create Account', '/register'],
    stats: [['Global', 'Community'], ['48h', 'Typical Reply'], ['Open', 'Partnerships']],
    sections: [
      ['General Inquiries', 'Ask about programs, clubs, resources, or learner access.'],
      ['Partnerships', 'Work with us to support youth innovation through mentorship, grants, or learning opportunities.'],
      ['Support', 'Get help with account access, applications, and dashboard features.'],
    ],
    cards: [
      ['Email', 'hello@c360innovation.org'],
      ['Partnerships', 'partners@c360innovation.org'],
      ['Location', 'Serving learners and partners globally.'],
    ],
  },
  '/competitions': {
    title: 'Competitions',
    eyebrow: 'Challenge Yourself',
    description: 'Discover innovation challenges, pitch events, and project competitions for young builders.',
    cta: ['Prepare With Learn', '/learn'],
    stats: [['8+', 'Annual Challenges'], ['Global', 'Participation'], ['Mentor', 'Feedback']],
    sections: [
      ['Innovation Challenges', 'Solve real-world problems through guided briefs and team submissions.'],
      ['Pitch Events', 'Practice communicating your idea clearly to mentors, judges, and partners.'],
      ['Showcases', 'Share prototypes, research, and project outcomes with the wider community.'],
    ],
    cards: [
      ['Digital Solutions Hackathon', 'Prototype a practical digital tool in a focused sprint.'],
      ['Sustainability Challenge', 'Create solutions for climate and circular economy problems.'],
      ['Youth Enterprise Pitch', 'Develop and present a venture concept.'],
    ],
  },
  '/financial-literacy': {
    title: 'Financial Literacy',
    eyebrow: 'Money Skills',
    description: 'Learn budgeting, saving, pricing, funding, and financial decision-making for life and enterprise.',
    cta: ['Open Learning Workspace', '/learn'],
    stats: [['5', 'Modules'], ['Practical', 'Exercises'], ['Youth', 'Focused']],
    sections: [
      ['Personal Finance', 'Build habits for budgeting, saving, and managing money confidently.'],
      ['Business Finance', 'Understand pricing, costs, revenue, and cash flow.'],
      ['Funding Readiness', 'Prepare for grants, partnerships, and responsible investment conversations.'],
    ],
    cards: [
      ['Budget Builder', 'Plan income, costs, savings, and priorities.'],
      ['Pricing Practice', 'Estimate costs and set sustainable prices.'],
      ['Funding Checklist', 'Prepare your documents and pitch for support.'],
    ],
  },
  '/incubation': {
    title: 'Apply For Incubation',
    eyebrow: 'From Idea To Launch',
    description: 'Get structured support to refine, validate, prototype, and pitch your innovation or venture.',
    cta: ['Apply Now', '/register'],
    stats: [['12 weeks', 'Guided Support'], ['Mentors', 'Assigned'], ['Demo Day', 'Included']],
    sections: [
      ['Validate', 'Test your assumptions with users and evidence.'],
      ['Prototype', 'Turn ideas into simple, testable solutions.'],
      ['Pitch', 'Tell a clear story about the problem, solution, model, and impact.'],
    ],
    cards: [
      ['Idea Review', 'Clarify your problem, user, and proposed solution.'],
      ['Mentor Sessions', 'Receive focused guidance from relevant experts.'],
      ['Demo Preparation', 'Prepare to present your progress and next ask.'],
    ],
  },
  '/mentorship': {
    title: 'Career Guidance & Mentorship',
    eyebrow: 'Guided Growth',
    description: 'Connect with mentors who help learners make better decisions, build skills, and move toward meaningful opportunities.',
    cta: ['Book A Session', '/mentorship-sessions'],
    stats: [['80+', 'Mentors'], ['1:1', 'Guidance'], ['Career', 'Support']],
    sections: [
      ['Career Clarity', 'Explore interests, strengths, pathways, and next steps.'],
      ['Skill Building', 'Get feedback on portfolios, projects, communication, and leadership.'],
      ['Opportunity Readiness', 'Prepare for internships, programs, competitions, and entrepreneurship.'],
    ],
    cards: [
      ['Portfolio Review', 'Improve how you present your projects and skills.'],
      ['Goal Setting', 'Create a practical growth plan with milestones.'],
      ['Mock Interviews', 'Practice communicating your strengths and experience.'],
    ],
  },
  '/mentorship-sessions': {
    title: 'Mentorship Sessions',
    eyebrow: 'Book & Prepare',
    description: 'Manage mentorship sessions and prepare focused questions so every conversation creates progress.',
    cta: ['Open Dashboard', '/dashboard'],
    stats: [['30 min', 'Typical Session'], ['Focused', 'Agenda'], ['Action', 'Plan']],
    sections: [
      ['Upcoming Sessions', 'Track your scheduled mentor conversations.'],
      ['Preparation', 'Write goals, questions, and context before the call.'],
      ['Follow Up', 'Turn advice into concrete actions and deadlines.'],
    ],
    cards: [
      ['Career Planning', 'Discuss skills, roles, and learning pathways.'],
      ['Project Feedback', 'Get advice on prototypes, research, or pitches.'],
      ['Enterprise Guidance', 'Review business models and go-to-market plans.'],
    ],
  },
  '/research': {
    title: 'Research & Innovation',
    eyebrow: 'Evidence Into Action',
    description: 'Support youth-led inquiry, experimentation, and practical research that informs better solutions.',
    cta: ['Use Learn Workspace', '/learn'],
    stats: [['Inquiry', 'Led'], ['Prototype', 'Driven'], ['Impact', 'Focused']],
    sections: [
      ['Problem Research', 'Understand users, contexts, and root causes.'],
      ['Experimentation', 'Test ideas through small pilots and prototypes.'],
      ['Knowledge Sharing', 'Document findings and share lessons with the community.'],
    ],
    cards: [
      ['Research Canvas', 'Frame questions, assumptions, methods, and findings.'],
      ['Interview Guide', 'Prepare better user conversations.'],
      ['Insight Report', 'Turn observations into decisions.'],
    ],
  },
  '/partnerships': {
    title: 'Grants & Partnerships',
    eyebrow: 'Grow Together',
    description: 'Partner with C360 to support youth innovation through mentorship, funding, programs, and learning resources.',
    cta: ['Contact Us', '/contact'],
    stats: [['12+', 'Partners'], ['Global', 'Network'], ['Youth', 'Impact']],
    sections: [
      ['Mentorship Partners', 'Contribute expertise and guidance to young innovators.'],
      ['Program Partners', 'Co-create learning opportunities, challenges, and incubation pathways.'],
      ['Grant Partners', 'Support promising youth-led projects and community solutions.'],
    ],
    cards: [
      ['Sponsor A Club', 'Support recurring project-based learning.'],
      ['Host A Challenge', 'Invite youth teams to solve meaningful problems.'],
      ['Fund A Project', 'Help promising ideas move from prototype to impact.'],
    ],
  },
  '/profile': {
    title: 'My Profile',
    eyebrow: 'Your Account',
    description: 'Manage your learning profile, interests, goals, and saved progress across C360.',
    cta: ['Go To Dashboard', '/dashboard'],
    stats: [['Personal', 'Profile'], ['Saved', 'Progress'], ['Learning', 'Goals']],
    sections: [
      ['Personal Details', 'Keep your name, contact, and profile information up to date.'],
      ['Learning Interests', 'Choose the topics and tracks that matter most to you.'],
      ['Progress', 'Review activity across programs, clubs, mentorship, and learning.'],
    ],
    cards: [
      ['Edit Profile', 'Update personal and account details.'],
      ['Set Goals', 'Define what you want to build and learn.'],
      ['View Activity', 'See saved resources and recent progress.'],
    ],
  },
  '/my-club': {
    title: 'My Club',
    eyebrow: 'Club Workspace',
    description: 'Track your club, activities, members, and project progress in one place.',
    cta: ['Explore Clubs', '/clubs'],
    stats: [['Active', 'Membership'], ['Projects', 'In Progress'], ['Peer', 'Learning']],
    sections: [
      ['Club Overview', 'See your club focus, meeting rhythm, and current priorities.'],
      ['Projects', 'Follow the ideas and prototypes your club is building.'],
      ['Members', 'Collaborate with peers and club leaders.'],
    ],
    cards: [
      ['Meeting Notes', 'Capture decisions and next steps.'],
      ['Project Board', 'Organize ideas and tasks.'],
      ['Club Resources', 'Access guides for running sessions.'],
    ],
  },
  '/notifications': {
    title: 'Notifications',
    eyebrow: 'Updates',
    description: 'Review program reminders, mentorship updates, resource alerts, and club activity.',
    cta: ['Open Dashboard', '/dashboard'],
    stats: [['3', 'Unread'], ['Today', 'Latest'], ['Action', 'Ready']],
    sections: [
      ['Mentorship', 'Session confirmations, reminders, and follow-up notes.'],
      ['Learning', 'New resources, program updates, and recommended next steps.'],
      ['Clubs', 'Meeting reminders, project updates, and announcements.'],
    ],
    cards: [
      ['Session Confirmed', 'Your mentorship session has been confirmed.'],
      ['New Resource', 'A grant opportunity was added to resources.'],
      ['Club Update', 'Your club meeting has a new agenda.'],
    ],
  },
};
